### ISSUE TITLE
child.execSync returns a Buffer

### ISSUE THREAD

**Issue by sgen** [agentk/fontfacegen#14]
At least it does on Ubuntu 15.10.

This creates a where [getFontName()](https://github.com/agentk/fontfacegen/blob/master/fontfacegen.js#L232),
[getFontWeight()](https://github.com/agentk/fontfacegen/blob/master/fontfacegen.js#L240),
[getFontStyle()](https://github.com/agentk/fontfacegen/blob/master/fontfacegen.js#L251), return false, and errors thrown by [fontforge](https://github.com/agentk/fontfacegen/blob/master/fontfacegen.js#L295) are not properly handled.

**Comment by agentk** [comment]
Fixed in #13
