### ISSUE TITLE
Push Linux support to NPM

### ISSUE THREAD

**Issue by sgen** [agentk/fontfacegen#15]
Downloading fontfacegen with npm results in a version pre Linux compatibility commit.

To replicate:
```bash
npm install fontfacegen
cat fontfacegen.js
```

No isLinux check etc.

Just in case its me:

OS: Ubuntu 15.10
fontfacegen: 1.7
NPM: 3.6.0

**Comment by agentk** [comment]
Pushed 0.1.8 to npm. Ready for testing on Linux again ;-)
