### ISSUE TITLE
fontfacegen@0.1.8 dependencies not installed

### ISSUE THREAD

**Issue by thekelvinliu** [agentk/fontfacegen#20]
I'm using fontfacegen in one of my projects, and it's been incredibly helpful. There's just a small issue/bug you may or may not be aware of. Version 0.1.8 on [npm](https://www.npmjs.com/package/fontfacegen) doesn't install [ttf2woff2](https://www.npmjs.com/package/ttf2woff2) as a dependency. The `package.json` for fontfacegen@0.1.8 lists ttf2woff2 as a devDependency rather than an actual dependency. From the looks of the repo here, it looks like there's been pretty significant code restructuring, but would it be possible to patch this bug in the current release?

**Comment by sgen** [comment]
@agentk Can you give me publish privileges? Ill fix this and a couple other issues.

**Comment by sgen** [comment]
Fix has been pushed, just waiting on npm publish privs. You can use `npm install http://github.com/agentk/fontfacegen.git` in the meantime.
