### ISSUE TITLE
[ttf2svg] Warning: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by julianxhokaxhiu** [agentk/fontfacegen#22]
As the title says, If I try to install

```
npm install -g ttf2svg
```

I get that error. If not I get
```
which: no ttf2svg in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
```

Any clue? Thanks in advance

---

Found the issue but I need @agentk or @sgen to fix this. These [two lines](https://github.com/agentk/fontfacegen/blob/master/lib/fontfacegen.js#L20-21) are causing the issue. In fact on NPM we still have the 0.1.8 version which is anyway broken because is asking for

```
createDestinationDirectory(path.dirname(config.less));
```

which is not there in the `config` dictionary. Please fix this asap otherwise a lot of projects, including mine will be affected and we're literally on our bare feet because of this issue.

Thanks in advance!

**Comment by julianxhokaxhiu** [comment]
@agentk are you still supporting this project?

**Comment by julianxhokaxhiu** [comment]
@agentk I actually fixed a typo which was going to break also v0.1.9. You can push it to NPM, I tested it and it's working. If you can also please update `grunt-fontfacegen` so it uses this latest version.

Thank you!

**Comment by sgen** [comment]
Checking this out now

**Comment by sgen** [comment]
The fix is up on github, you can use `npm install http://github.com/agentk/fontfacegen` in the meantime

**Comment by julianxhokaxhiu** [comment]
New update pushed to NPM. The issue is now fixed :) Enjoy
