### ISSUE TITLE
Mac OS Test Volunteer

### ISSUE THREAD

**Issue by sgen** [agentk/fontfacegen#30]
We need someone to test patches on Mac OS prior to their release.

**Comment by agentk** [comment]
I'm on Mac, but it there are any specific tests, we can automate all of it through Travis CI.
Travis has good support for Ubuntu and OS X, so that still leaves other Linux distros and Windows. I'm not sure how we would even start automating those.

**Comment by sgen** [comment]
I think there are other issues with Windows (fontforge, ttf2svg equivalents etc). It might be best to not support Windows for now and just use Travis CI.

**Comment by sgen** [comment]
Use Travis CI
