### ISSUE TITLE
Properly install dependencies on All OS

### ISSUE THREAD

**Issue by sgen** [agentk/fontfacegen#32]
We should look into automating the installation of our dependencies (ttf2svg, batik-ttf2svg etc)

**Comment by sgen** [comment]
agentk/gulp-fontgen#17

**Comment by perrin4869** [comment]
How about making `ttf2eot` a dependency too? Maybe we should send a PR over there to expose a programmatic API too. Although not strictly necessary.

**Comment by perrin4869** [comment]
Closed by #36 (`fontforge` still needs to be manually installed)
