### ISSUE TITLE
Test batik-ttf2svg and ttf2svg on all OS

### ISSUE THREAD

**Issue by sgen** [agentk/fontfacegen#33]
batik-ttf2svg may not be necessary and is causing a few headaches.

Test removing / replacing it with ttf2svg.

**Comment by perrin4869** [comment]
I could just confirm, `ttf2svg` works on OS X, so `batik-ttf2svg` is unnecessary. Will put together a PR fixing this soon.

**Comment by perrin4869** [comment]
Closed by #36
