### ISSUE TITLE
empty eot files

### ISSUE THREAD

**Issue by terion-name** [agentk/fontfacegen#4]
MacOS X 10.10.3

Task:

```coffee
gulp.task 'fonts', ->

  fontfacegen = require('fontfacegen')
  fs = require('fs')
  path = require('path')
  concat = require('concat-files')

  fonts = fs.readdirSync('src/fonts/')
  cssFiles = []
  for font in fonts
    extension = path.extname(font)
    fontname = path.basename(font, extension)
    fontfacegen
      source:  path.join('src/fonts/', font),
      dest: 'build/fonts/',
      collate: true
      css: "build/fonts/#{fontname}.css"
      css_fontpath: "../fonts/"
```

Results in:
![2015-05-19 18 50 47](https://cloud.githubusercontent.com/assets/1060205/7707359/fea99f8a-fe57-11e4-9a86-b21c6b63bd14.png)
↑ eot is empty =(

Deps are installed:
```bash
$ brew install fontforge ttf2eot batik
Warning: fontforge-20120731_1 already installed
Warning: ttf2eot-0.0.2-2 already installed
Warning: batik-1.7 already installed
```

**Comment by Awea** [comment]
Sadly, I get the same issue here.

**Comment by Awea** [comment]
I've just tested the command used by this script : 

`/usr/local/bin/ttf2eot "/a/path/foo.ttf" > "/a/path/foo.eot"`

It works well but inside the node script it doesn't. Any idea @agentk ?

**Comment by agentk** [comment]
I think @BsWiM's solution of using the node provided exec is the best solution. It's merged in now. I'll be pushing out npm updates for fontfacegen, gulp-fontgen and grunt-fontgen tonight.
