### ISSUE TITLE
no ending of task 

### ISSUE THREAD

**Issue by alexanderkatkov** [agentk/fontfacegen#7]
Hi.
Tried to create font-face from font 28kb weight, ttf format (also tried another fonts).

this is task in gulpfile.js

gulp.task(
'fonts', ['del-fonts'], function(){
return gulp.src(path.src.fonts)
.pipe(plumber({errorHandler: onError})) // plumber
.pipe(gulpfontgen({
/*collate: true,
css_fontpath: path.src.fontface,*/
dest: path.build.fonts
}))
.pipe(gulp.dest(path.build.fonts))
.pipe(browserSync.reload({ stream:true }))
.pipe(notify({message: 'FONTS task complete', onLast: true}));
});

task start to run and no finishing until I break it, tried to wait about 30mins.
[11:23:14] Starting 'del-fonts'...
[11:23:14] Finished 'del-fonts' after 8.47 ms
[11:23:14] Starting 'fonts'...
[11:23:14] Finished 'fonts' after 19 ms

no fonts created, no errors in console

CPU is Intel I5 so it seems to be fast enough.

**Comment by agentk** [comment]
Hi @alexanderkatkov, the fix for this is merged now along with #4. Pushing out npm updates very soon. Just got to do some more tests.
